$env:TRAIN_SYMBOL="EURUSD"
$env:TRAIN_TOTAL_TIMESTEPS="25000"
$env:TRAIN_NUM_ENVS="4"
$env:TRAIN_PROGRESS_VERBOSE="1"
$env:TRAIN_LOG_INTERVAL="1"
$env:TRAIN_HEARTBEAT_EVERY_STEPS="5000"
$env:TRAIN_FORCE_DUMMY_VEC="0"
$env:TRAIN_DEBUG_ALLOW_BASELINE_BYPASS="1"

# Run training
python train_agent.py
